######################################################################
# Automatically generated by qmake (2.01a) Mi 1. Apr 23:54:31 2015
######################################################################

QT       += xml

CONFIG += qtestlib
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QMAKE_LIBDIR += ../release
LIBS += cl2.lib


# Input
SOURCES += test_log.cpp
SOURCES += test_xml.cpp
